server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA: qualquer rota cai no index
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Proxy para a API (mesmo host em produção; nome do service no K8s/compose)
  location /api/ {
    proxy_pass http://api:3001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Request-Id $request_id;
    client_max_body_size 30m;
  }

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;
}
